### ISSUE TITLE
mddf-tools-1.7 throws NullPointerException on command line invocation

### ISSUE THREAD

**Issue by plondino** [MovieLabs/mddf#1] opened 2020-01-22 22:46 UTC
I get a NullPointerException whenever I try to run the binaries\mddf-tools-1.7.jar:

`C:\code\poc\mddf> java -jar .\binaries\mddf-tools-1.7.jar --logFile C:\temp -logLevel warn -f C:\code\schema\MovieLabs\examples\MMC_Example1_simple.xml -v`

`java.lang.NullPointerException
        at com.movielabs.mddflib.logging.DefaultLogging.clearLog(DefaultLogging.java:304)
        at com.movielabs.mddf.tools.ValidationController.validate(ValidationController.java:325)
        at com.movielabs.mddf.tools.ToolLauncher.runNonInteractive(ToolLauncher.java:226)
        at com.movielabs.mddf.tools.ToolLauncher.execute(ToolLauncher.java:166)
        at com.movielabs.mddf.tools.ToolLauncher.main(ToolLauncher.java:90)
0: Fatal: Manifest: line N.A : Unspecified Exception while validating`

This is using the MMC example on the website. It validates online or using the 1.6.0 jar on the command line.

**Comment by ljlevin** [comment] 2020-01-27 16:03
The bug is in the logging initialization sequence when running in batch mode. I'll add it to the to-do list for the next release but until then you should have no problem running in the interactive mode as logging is handled by a different module.

**Comment by plondino** [comment] 2020-04-20 16:40
Just checking if there's any update on this. This is still affecting v1.8.0.1.

The interactive mode works, but we'd really like to build this code into our supply chain to automatically validate MMC coming in the door.

Thanks for all the effort that's gone into this library.

**Comment by ljlevin** [comment] 2020-04-21 21:32
This should now be fixed (see the discussion on "NPE in mddf-tools v1.8 startup in non-interactive mode"). The two have a the same root cause I believe. I'm going to close this issue but leave the other one open for now so if you still see a problem, post on the other thread.
Sorry it took so long to close this out. Feb and March turned out to be a bit chaotic. Thanks for being patient.

**Closed by ljlevin** 2020-04-21 21:32 UTC
